# Generated by Django 5.2.6 on 2025-09-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='Depertment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='Passing_Year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='Contact',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='Depertment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
