# Generated by Django 5.2.7 on 2025-10-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_studentmodel_depertment_studentmodel_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Depertment',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='Contact',
            field=models.IntegerField(null=True),
        ),
    ]
